# Generated by Django 5.1.15 on 2026-09-16 20:17

from django.db import migrations, models


def mark_existing_as_processed(apps, schema_editor):
    """
    Receipts that already carry extracted data were processed before this
    field existed. Without this they would all default to 'pending' and the
    new worker would re-run the model over the entire history.
    """
    Receipt = apps.get_model('receipts', 'Receipt')
    Receipt.objects.exclude(extracted_data=None).update(status='success')
    Receipt.objects.filter(extracted_data=None).update(
        status='failed',
        error_message='Uploaded before background processing was added.')


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='receipt',
            name='content_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='receipt',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='receipt',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.RunPython(mark_existing_as_processed, noop),
    ]
