# Generated by Django 5.1.15 on 2026-09-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0003_receipt_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='corrected_file',
            field=models.FileField(blank=True, upload_to='receipts/corrected/'),
        ),
    ]
