# Generated by Django 5.1.15 on 2026-09-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0004_receipt_corrected_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='scanned_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
